name: Build Fast (Windows)

on:
  workflow_dispatch:

env:
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        cache: true

    - name: Build Windows (x64)
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/release

        # 64-bit сборка
        cmake -B ${{ github.workspace }}/build_x64 \
              -DCMAKE_BUILD_TYPE=Release \
              -S ${{ github.workspace }} \
              -DCMAKE_C_COMPILER_LAUNCHER=sccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
              -DOUTDIR=${{ github.workspace }}/release \
              -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake \
              -DVCPKG_TARGET_TRIPLET=x64-windows \
              -A x64
        cmake --build ${{ github.workspace }}/build_x64 --config Release --target csgo csgo_gc

        # 32-bit сборка (если нужна)
        cmake -B ${{ github.workspace }}/build_x86 \
              -DCMAKE_BUILD_TYPE=Release \
              -S ${{ github.workspace }} \
              -DCMAKE_C_COMPILER_LAUNCHER=sccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
              -DOUTDIR=${{ github.workspace }}/release \
              -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake \
              -DVCPKG_TARGET_TRIPLET=x86-windows \
              -A Win32
        cmake --build ${{ github.workspace }}/build_x86 --config Release --target srcds csgo_gc

    - name: Package (only essential files)
      shell: bash
      run: |
        cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/release/
        mkdir -p $GITHUB_WORKSPACE/release/csgo_gc
        cp $GITHUB_WORKSPACE/examples/config.txt $GITHUB_WORKSPACE/release/csgo_gc/
        cp $GITHUB_WORKSPACE/examples/inventory.txt $GITHUB_WORKSPACE/release/csgo_gc/
        cp $GITHUB_WORKSPACE/examples/price_sheet.txt $GITHUB_WORKSPACE/release/csgo_gc/
        cp $GITHUB_WORKSPACE/examples/unusual_loot_lists.txt $GITHUB_WORKSPACE/release/csgo_gc/

    - name: Zip artifacts
      shell: bash
      run: |
        OUTNAME="csgo_gc-windows-latest.zip"
        (cd release && zip -r "../${OUTNAME}" .)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact-windows-latest
        path: ${{ github.workspace }}/csgo_gc-windows-latest.zip

  publish:
    if: github.event_name != 'pull_request'
    needs: build-windows
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create continuous release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          TAG=continuous-fast
          files=( $(find artifacts -type f -name "*.zip") )

          if [ ${#files[@]} -gt 0 ]; then
            gh release delete "$TAG" --cleanup-tag --repo "$REPO" --yes || true
            sleep 10s
            gh release create "$TAG" --repo "$REPO" \
              --title "Continuous Fast Build (Windows)" \
              --notes "$SHA" \
              --target "$SHA"
            gh release upload "$TAG" --repo "$REPO" "${files[@]}" --clobber
          fi
